[package]
edition = "2021"
name = "memory"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
cfg-if = "1.0"
common = {path = "../../common"}
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
systemstat = {version = "0.2"}
